export interface EventItem {
  id: string;
  slug: string;
  title: string;
  date: string;
  time: string;
  location: string;
  schoolPartner: string;
  description: string;
  fullDescription: string;
  imageSrc: string;
  badge: string;
  badgeColor: string;
  category: string;
  status: "upcoming" | "ongoing" | "completed";
}

export const EVENTS: EventItem[] = [
  {
    id: "1",
    slug: "eco-restoration-plantation-drive",
    title: "Eco-Restoration Plantation Drive",
    date: "June 05, 2026",
    time: "09:00 AM - 01:00 PM",
    location: "Barjora, Bankura District",
    schoolPartner: "Barjora High School",
    description: "Planting 1,000+ native saplings in partnership with students to restore local greenery and combat soil erosion.",
    fullDescription: "Join us for our flagship environmental restoration event. In partnership with Barjora High School, we aim to plant over 1,000 indigenous saplings across degraded community lands in Bankura district. This initiative combats soil erosion, restores local biodiversity, and creates green corridors for wildlife. Volunteers will receive hands-on training in sapling planting techniques, soil preparation, and post-planting care. All materials including saplings, tools, and compost will be provided. Refreshments and certificates of participation will be given to all volunteers.",
    imageSrc: "/Assets/Borjora_HS_01.png",
    badge: "Environment",
    badgeColor: "bg-primary-900 text-white border-primary-400",
    category: "Environment",
    status: "upcoming",
  },
  {
    id: "2",
    slug: "sakti-life-saving-blood-camp",
    title: "Sakti Life-Saving Blood Camp",
    date: "June 14, 2026",
    time: "10:00 AM - 04:00 PM",
    location: "Narayana Healthcare Center, Kolkata",
    schoolPartner: "Narayana Group",
    description: "Annual blood collection drive in collaboration with local medical authorities to replenish emergency blood banks.",
    fullDescription: "Our annual blood donation camp brings together healthcare professionals, student volunteers, and community donors to address critical blood shortages in local hospitals. In collaboration with Narayana Healthcare, we ensure all donations meet clinical safety standards. Donors receive free health checkups, refreshments, and donor certificates. Every unit of blood collected can save up to three lives. This year's target is 500 units across a single day.",
    imageSrc: "/Assets/narayana_01.png",
    badge: "Health Camp",
    badgeColor: "bg-alert-500 text-white border-alert-500",
    category: "Healthcare",
    status: "upcoming",
  },
  {
    id: "3",
    slug: "dps-green-workshop-seminars",
    title: "DPS Green Workshop & Seminars",
    date: "June 22, 2026",
    time: "11:00 AM - 02:00 PM",
    location: "DPS Auditorium, Salt Lake",
    schoolPartner: "Delhi Public School",
    description: "Empowering young students through hands-on seminars on waste segregation, biodiversity, and eco-friendly lifestyles.",
    fullDescription: "An interactive workshop series designed to educate school students about environmental responsibility. Topics include waste segregation practices, understanding local biodiversity, water conservation techniques, and adopting eco-friendly daily habits. The workshop features hands-on activities, quiz competitions, and a student-led pledge for sustainable living. Materials and certificates provided to all participating students.",
    imageSrc: "/Assets/dps_01.png",
    badge: "Education",
    badgeColor: "bg-accent-500 text-primary-900 border-accent-500",
    category: "Education",
    status: "upcoming",
  },
  {
    id: "4",
    slug: "community-cleanliness-campaign",
    title: "Community Cleanliness Campaign",
    date: "July 01, 2026",
    time: "07:30 AM - 11:30 AM",
    location: "St Michael's Grounds and Suburbs",
    schoolPartner: "St Michael's School",
    description: "A community cleanup and sanitization campaign to create awareness around plastic pollution and community hygiene.",
    fullDescription: "A grassroots community cleanliness drive aimed at reducing plastic pollution and improving public hygiene in the St Michael's neighborhood. Volunteers will participate in systematic waste collection, plastic segregation, and awareness door-to-door campaigns. We will install temporary waste bins and distribute reusable bags to local households. Safety gloves, masks, and refreshments provided.",
    imageSrc: "/Assets/st_michale_01.png",
    badge: "Sanitation",
    badgeColor: "bg-primary-400 text-primary-900 border-primary-400",
    category: "Sanitation",
    status: "upcoming",
  },
  {
    id: "5",
    slug: "youth-leadership-sakti-camp",
    title: "Youth Leadership Sakti Camp",
    date: "July 12, 2026",
    time: "09:00 AM - 05:00 PM",
    location: "St Peter's Campus, Kolkata",
    schoolPartner: "St Peter's Academy",
    description: "Developing youth leadership skills for community development, emergency response, and peer-to-peer mental health support.",
    fullDescription: "A full-day leadership development camp focused on building the next generation of community leaders. Sessions cover public speaking, project management for social initiatives, emergency first aid response, and peer-to-peer mental health support techniques. The camp includes team-building exercises, mock campaign planning, and mentorship sessions with experienced NGO leaders.",
    imageSrc: "/Assets/st_peters_01.png",
    badge: "Youth Sakti",
    badgeColor: "bg-warning-500 text-white border-warning-500",
    category: "Youth",
    status: "upcoming",
  },
  {
    id: "6",
    slug: "beachwood-plantation-drive",
    title: "Beachwood Campus Green Drive",
    date: "May 15, 2026",
    time: "08:00 AM - 12:00 PM",
    location: "Beachwood Academy Grounds",
    schoolPartner: "Beachwood Academy",
    description: "Completed plantation of 500 saplings at Beachwood Academy as part of our campus greening initiative.",
    fullDescription: "A successful campus greening initiative completed at Beachwood Academy where 500 native saplings were planted across the school grounds. Students and faculty participated actively in the drive, learning about indigenous tree species and their ecological significance.",
    imageSrc: "/Assets/beachwood_01.png",
    badge: "Environment",
    badgeColor: "bg-primary-900 text-white border-primary-400",
    category: "Environment",
    status: "completed",
  },
  {
    id: "7",
    slug: "emergency-blood-drive-narayana",
    title: "Emergency Blood Drive at Narayana",
    date: "May 20, 2026",
    time: "09:00 AM - 03:00 PM",
    location: "Narayana Medical College",
    schoolPartner: "Narayana Group",
    description: "Emergency blood collection drive responding to a critical shortage at local hospitals.",
    fullDescription: "An emergency response blood donation camp organized in coordination with Narayana Medical College to address a critical blood shortage in Kolkata hospitals. Over 200 units were collected in a single day.",
    imageSrc: "/Assets/narayana_02.png",
    badge: "Health Camp",
    badgeColor: "bg-alert-500 text-white border-alert-500",
    category: "Healthcare",
    status: "completed",
  },
  {
    id: "8",
    slug: "dps-science-fair-sustainability",
    title: "DPS Science Fair for Sustainability",
    date: "May 28, 2026",
    time: "10:00 AM - 04:00 PM",
    location: "DPS Science Block, Salt Lake",
    schoolPartner: "Delhi Public School",
    description: "Student science fair focused on sustainable technology innovations and green energy projects.",
    fullDescription: "A student-led science fair showcasing innovative projects focused on sustainability, renewable energy, and environmental conservation. Over 50 student teams presented their projects to judges from academic and NGO backgrounds.",
    imageSrc: "/Assets/dps_02.png",
    badge: "Education",
    badgeColor: "bg-accent-500 text-primary-900 border-accent-500",
    category: "Education",
    status: "completed",
  },
];
